name: Amauri Bz
description: 
meta_description: "Amauri Bz"

markdown: redcarpet
pygments: true

baseurl: http://amauribz.github.io

logo: false
paginate: 15
permalink: /:title


# Details for the RSS feed generator
url:            'amauribz.github.io'
author:         'Amauri Bz'


